SENTINEL1_FIELDS = [
    "scene_id",
    "collection",
    "acquisition_datetime",
    "platform",
    "product_type",
    "instrument_mode",
    "polarizations",
    "orbit_direction",
    "absolute_orbit",
    "relative_orbit",
    "footprint_wkt",
    "aoi_coverage",
    "temporal_group",
    "accepted",
    "rejected_reason",
    "stac_item_url",
]

SENTINEL2_FIELDS = [
    "scene_id",
    "collection",
    "acquisition_datetime",
    "platform",
    "processing_level",
    "mgrs_tile",
    "cloud_cover",
    "footprint_wkt",
    "aoi_coverage",
    "temporal_group",
    "accepted",
    "rejected_reason",
    "stac_item_url",
]

PAIR_FIELDS = [
    "sensor",
    "pre_scene_id",
    "post_scene_id",
    "pre_acquisition_datetime",
    "post_acquisition_datetime",
    "pre_days_to_event",
    "post_days_after_event",
    "relative_orbit",
    "orbit_direction",
    "instrument_mode",
    "polarizations",
    "pre_aoi_coverage",
    "post_aoi_coverage",
    "pair_aoi_coverage",
    "rank",
    "recommended",
]
